name: Auto-Merge Parameter/Protocol After PR Approval

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write
  pull-requests: read

jobs:
  auto-merge-to-main-files:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Dependencies
      run: |
        pip install pyyaml jinja2 python-frontmatter mistune
    
    - name: Merge Pending Files to Main YAML
      run: |
        echo "🔄 Merging pending files..."
        python .github/scripts/merge_pending_files.py
        echo "✅ Merge completed!"
    
    - name: Generate Documentation
      run: |
        echo "🔄 Generating markdown documentation..."
        python generators/markdown_generator.py
        echo "✅ Markdown documentation generated!"
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "📝 Changes detected"
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "ℹ️ No changes to commit"
        fi
    
    - name: Commit Changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/parameters.yaml data/protocols.yaml
        git add output/markdown/ || echo "No markdown files to add"
        git status
        git commit -m "Auto-merge: Add approved parameter/protocol from PR + Generate docs"
        git push
    
    - name: No Changes
      if: steps.verify-changed-files.outputs.changed == 'false'
      run: |
        echo "ℹ️ No changes to commit - merge may have already been processed"