name: Auto-Merge Parameter/Protocol After PR Approval

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write
  pull-requests: read

jobs:
  auto-merge-to-main-files:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Dependencies
      run: |
        pip install pyyaml jinja2 python-frontmatter mistune
    
    - name: Merge Pending Files to Main YAML
      run: |
        python .github/scripts/merge_pending_files.py
    
    - name: Generate Documentation
      run: |
        echo "🔄 Generating markdown documentation..."
        python generators/markdown_generator.py
        echo "✅ Markdown documentation generated!"
    
    - name: Commit Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/parameters.yaml data/protocols.yaml output/markdown/
        git commit -m "Auto-merge: Add approved parameter/protocol from PR + Generate docs" || exit 0
        git push